name: Drive Sign-in

on:
  schedule:
    - cron: '0 5 * * *'  
  workflow_dispatch:  

jobs:
  sign_in:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set execution permission
      run: chmod +x my-script.sh
      
    - name: Run sign-in script
      run: ./my-script.sh
      env:
        ALI_REFRESH_TOKEN: ${{ secrets.ALI_REFRESH_TOKEN }}
        TY_USER: ${{ secrets.TY_USER }}
        TY_PWD: ${{ secrets.TY_PWD }}
        YOUDAO_COOKIE: ${{ secrets.YOUDAO_COOKIE }}
        PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
        SERVERCHAN_SENDKEY: ${{ secrets.SERVERCHAN_SENDKEY }}
        WECOM_TOKENS: ${{ secrets.WECOM_TOKENS }}
        WECOM_WEBHOOK: ${{ secrets.WECOM_WEBHOOK }}
        BARK_DEVICEKEY: ${{ secrets.BARK_DEVICEKEY }}
        FEISHU_DEVICEKEY: ${{ secrets.FEISHU_DEVICEKEY }}
        YOUDAO_USER: ${{ secrets.YOUDAO_USER }}
        REDIS_INFO: ${{ secrets.REDIS_INFO }}
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        QYWX_AM: ${{ secrets.QYWX_AM }}

      

    
